// Generated by CoffeeScript 1.3.1
(function() {
  var leaflet, models, nowjs,
    __hasProp = {}.hasOwnProperty;

  models = require('./models');

  nowjs = require('now');

  leaflet = require('./lib/leaflet-custom-src.js');

  module.exports = function(app, SessionModel) {
    var CUser, aUsers, bridge, cUsers, everyone, getWhoCanSee;
    everyone = nowjs.initialize(app);
    bridge = require('./bridge')(everyone, SessionModel);
    everyone.now.setCurrentWorld = function(currentWorldId) {
      var group;
      if (currentWorldId) {
        group = nowjs.getGroup(currentWorldId).addUser(this.user.clientId);
        return this.now.currentWorldId = currentWorldId;
      } else {
        return this.now.currentWorldId = false;
      }
    };
    cUsers = {};
    aUsers = {};
    nowjs.on('connect', function() {
      var cid, nowUser, sid, userId, _ref,
        _this = this;
      nowUser = this.user;
      sid = decodeURIComponent(this.user.cookie['connect.sid']);
      cid = this.user.clientId;
      if ((_ref = this.user.session) != null ? _ref.auth : void 0) {
        userId = this.user.session.auth.userId;
        cUsers[cid] = {
          sid: sid,
          userId: userId,
          login: this.user.login
        };
        aUsers[userId] = {
          sid: sid,
          cid: cid
        };
        models.User.findById(userId, function(err, doc) {
          cUsers[cid] = {
            sid: sid,
            userId: userId,
            login: doc.login
          };
          aUsers[userId] = {
            sid: sid,
            cid: cid,
            login: doc.login
          };
          return nowUser.login = doc.login;
        });
      } else {
        cUsers[cid] = {
          sid: sid
        };
        SessionModel.findOne({
          'sid': sid
        }, function(err, doc) {
          var data;
          data = JSON.parse(doc.data);
          cUsers[cid] = {
            sid: sid,
            userId: doc._id
          };
          return _this.user.soid = doc._id;
        });
      }
      return true;
    });
    nowjs.on('disconnect', function() {
      var _ref;
      console.log('disconenect -----------------');
      delete cUsers[this.user.clientId];
      if ((_ref = this.user.session) != null ? _ref.auth : void 0) {
        delete aUsers[this.user.session.auth.userId];
        console.log('removing authd disconnected user');
      }
      return console.log('removing disconnected user');
    });
    everyone.now.setBounds = function(bounds) {
      var b;
      b = new leaflet.L.Bounds(bounds.max, bounds.min);
      return cUsers[this.user.clientId].bounds = b;
    };
    everyone.now.setClientStateFromServer = function(callback) {
      if (this.user.session) {
        return callback(this.user.session);
      }
    };
    everyone.now.setSelectedCell = function(cellPoint) {
      var cid, user;
      if (!this.now.currentWorldId) {
        return false;
      }
      cid = this.user.clientId;
      cUsers[cid].selected = cellPoint;
      user = this.user;
      return getWhoCanSee(cellPoint, this.now.currentWorldId, function(toUpdate) {
        var i, update, _results;
        _results = [];
        for (i in toUpdate) {
          if (i !== cid) {
            update = cUsers[cid];
            if (user.session) {
              update.color = user.session.color;
            }
            update.cid = cid;
            _results.push(nowjs.getClient(i, function() {
              return this.now.drawCursors(update);
            }));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      });
    };
    everyone.now.writeCell = function(cellPoint, content) {
      var cid, currentWorldId;
      if (!this.now.currentWorldId) {
        return false;
      }
      currentWorldId = this.now.currentWorldId;
      cid = this.user.clientId;
      bridge.processRite(cellPoint, content, this.user, currentWorldId, function(commandType, rite, cellPoint, cellProps) {
        if (rite == null) {
          rite = false;
        }
        if (cellPoint == null) {
          cellPoint = false;
        }
        if (cellProps == null) {
          cellProps = false;
        }
        return getWhoCanSee(cellPoint, currentWorldId, function(toUpdate) {
          var i, _results;
          _results = [];
          for (i in toUpdate) {
            if (rite) {
              _results.push(nowjs.getClient(i, function() {
                return this.now.drawRite(commandType, rite, cellPoint, cellProps);
              }));
            } else {
              _results.push(void 0);
            }
          }
          return _results;
        });
      });
      return true;
    };
    everyone.now.getTile = function(absTilePoint, numRows, callback) {
      var _this = this;
      if (!this.now.currentWorldId) {
        return false;
      }
      return models.Cell.where('world', this.now.currentWorldId).where('x').gte(absTilePoint.x).lt(absTilePoint.x + numRows).where('y').gte(absTilePoint.y).lt(absTilePoint.y + numRows).populate('current').run(function(err, docs) {
        var c, pCell, results, _i, _len;
        results = {};
        if (docs.length) {
          for (_i = 0, _len = docs.length; _i < _len; _i++) {
            c = docs[_i];
            if (c.current) {
              pCell = {
                x: c.y,
                y: c.y,
                contents: c.current.contents,
                props: c.current.props
              };
              results["" + c.x + "x" + c.y] = pCell;
            }
          }
          return callback(results, absTilePoint);
        } else {
          return callback(results, absTilePoint);
        }
      });
    };
    getWhoCanSee = function(cellPoint, worldId, cb) {
      return nowjs.getGroup(worldId).getUsers(function(users) {
        var i, toUpdate, _i, _len, _ref, _ref1;
        toUpdate = {};
        if (worldId) {
          for (_i = 0, _len = users.length; _i < _len; _i++) {
            i = users[_i];
            if ((_ref = cUsers[i]) != null ? (_ref1 = _ref.bounds) != null ? _ref1.contains(cellPoint) : void 0 : void 0) {
              toUpdate[i] = cUsers[i];
            }
          }
        }
        return cb(toUpdate);
      });
    };
    everyone.now.getCloseUsers = function(cb) {
      var aC, cid, closeUsers;
      if (!this.now.currentWorldId) {
        return false;
      }
      console.log('getCloseUsers called');
      closeUsers = [];
      cid = this.user.clientId;
      aC = cUsers[cid].selected;
      nowjs.getGroup(this.now.currentWorldId).getUsers(function(users) {
        var distance, i, key, u, uC, value, _i, _len, _ref;
        for (_i = 0, _len = users.length; _i < _len; _i++) {
          i = users[_i];
          uC = cUsers[i].selected;
          distance = Math.sqrt((aC.x - uC.x) * (aC.x - uC.x) + (aC.y - uC.y) * (aC.y - uC.y));
          console.log(distance);
          if (distance < 1000 && (i !== cid)) {
            u = {};
            _ref = cUsers[i];
            for (key in _ref) {
              if (!__hasProp.call(_ref, key)) continue;
              value = _ref[key];
              u[key] = value;
            }
            u.distance = distance;
            if (cUsers[i].login) {
              u.login = cUsers[i].login;
            }
            closeUsers.push(u);
          }
        }
        return cb(closeUsers);
      });
      return true;
    };
    everyone.now.submitFeedback = function(f, t) {
      var feedback;
      this.now.insertMessage('Thanks', 'We appreciate your feedback');
      feedback = new models.Feedback({
        contents: f,
        t: t
      });
      return feedback.save(function(err) {
        if (err) {
          return console.log(err);
        }
      });
    };
    everyone.now.setUserOption = function(type, payload) {
      var cid, userId,
        _this = this;
      console.log('setUserOption', type, payload);
      if (type = 'color') {
        cid = this.user.clientId;
        cUsers[cid].color = payload;
        this.user.session.color = payload;
        this.user.session.save();
        if (this.user.session.auth) {
          userId = this.user.session.auth.userId;
          return models.User.findById(userId, function(err, doc) {
            if (err) {
              console.log(err);
            }
            doc.color = payload;
            doc.save();
            console.log('USER COLORCHANGE', doc);
            return _this.now.insertMessage('hi', 'nice color');
          });
        }
      }
    };
    models.User.prototype.on('receivedEcho', function(rite) {
      var userId;
      if (aUsers[this._id]) {
        userId = this._id;
        rite.getOwner(function(err, u) {
          if (err) {
            console.log(err);
          }
          return nowjs.getClient(aUsers[userId].cid, function() {
            if (u) {
              return this.now.insertMessage('Echoed!', "" + u.login + " echoed what you said!");
            } else {
              return this.now.insertMessage('Echoed!', "Someone echoed what you said!");
            }
          });
        });
      }
      return true;
    });
    models.User.prototype.on('receivedOverRite', function(rite) {
      var userId;
      if (aUsers[this._id]) {
        userId = this._id;
        rite.getOwner(function(err, u) {
          if (err) {
            console.log(err);
          }
          return nowjs.getClient(aUsers[userId].cid, function() {
            if (u) {
              return this.now.insertMessage('Over Written', "Someone called " + u.login + " is writing over your cells. Click for more info");
            } else {
              return this.now.insertMessage('Over Written', "Someone is writing over your cells. Click for more info");
            }
          });
        });
      }
      return true;
    });
    CUser = (function() {
      var allByCid, allBySid, allByUid;

      CUser.name = 'CUser';

      allByCid = {};

      allBySid = {};

      allByUid = {};

      CUser.byCid = function(cid) {
        return allByCid[cid];
      };

      CUser.bySid = function(sid) {
        return allBy[sid];
      };

      CUser.byUid = function(uid) {
        return allByUid[uid];
      };

      function CUser(nowUser) {
        var _ref,
          _this = this;
        this.nowUser = nowUser;
        this.cid = this.nowUser.clientId;
        this.sid = decodeURIComponent(this.nowUser.cookie['connect.sid']);
        if ((_ref = nowUser.session) != null ? _ref.auth : void 0) {
          this.uid = nowUser.session.auth.userId;
          models.User.findById(this.uid, function(err, doc) {
            _this.login = doc.login;
            return _this.nowUser.login = doc.login;
          });
        } else {
          SessionModel.findOne({
            'sid': this.sid
          }, function(err, doc) {
            _this.uid = doc._id;
            return _this.nowUser.soid = doc._id;
          });
        }
        allByCid[this.cid] = this;
        allBySid[this.sid] = this;
        allByUid[this.uid] = this;
      }

      CUser.prototype.destructor = function() {
        delete allByCid[this.cid];
        delete allBySid[this.sid];
        delete allByUid[this.uid];
        return delete this.nowUser;
      };

      return CUser;

    })();
    exports.CUser = CUser;
    return true;
  };

}).call(this);
